site_tb/site_tb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tickets.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site_tb/tickets/urls.py
from django.urls import path
from . import views

urlpatterns = [path('', views.TicketView.as_view()),
               path('<slug:ticket_slug>/', views.TicketDetail.as_view(), name='ticket'),
               path('review/<int:pk>/', views.AddComments.as_view(), name='add_comments')]

site_tb/tickets/models.py
from django.db import models
from django.urls import reverse


class Ticket(models.Model):
    objects = None
    slug = models.SlugField(max_length=250, unique=True, db_index=True)
    title = models.CharField('Номер билета', max_length=100)
    author = models.CharField('Автор', max_length=100)
    date = models.DateField('Дата публикации')
    img = models.ImageField('Изображение', upload_to='image/%Y')

    class Meta:
        verbose_name = 'Билет'
        verbose_name_plural = 'Билеты'

    def __str__(self):
        return f'{self.title}'

    def get_absolute_url(self):
        return reverse('ticket', kwargs={'ticket_slug': self.slug})


class Question(models.Model):
    text_questions = models.TextField('Текст вопроса')
    question = models.ForeignKey(Ticket, verbose_name='Публикация', on_delete=models.CASCADE)
    img = models.ImageField('Изображение', upload_to='image/%Y', blank=True)

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'

    def __str__(self):
        return f'{self.text_questions}'


class Answer(models.Model):
    text_answer = models.TextField('Текст ответа')
    answer = models.ForeignKey(Question, verbose_name='Публикация', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Ответ'
        verbose_name_plural = 'Ответы'

    def __str__(self):
        return f'{self.text_answer}'


class Comments(models.Model):
    """Комментарий"""
    email = models.EmailField()
    name = models.CharField('Имя', max_length=50)
    text_comments = models.TextField('Текст комментария')
    post = models.ForeignKey(Ticket, verbose_name='Публикация', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return f'{self.name}, {self.post}'

site_tb/tickets/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from .form import CommentsForm
from .models import Ticket


class TicketView(View):
    def get(self, request):
        tickets = Ticket.objects.all()
        return render(request, 'site_tb/site_tb.html', {'ticket_list': tickets})


class TicketDetail(View):
    def get(self, request, ticket_slug):
        ticket = Ticket.objects.get(slug=ticket_slug)
        return render(request, 'site_tb/question.html', {'ticket': ticket})


class AddComments(View):
    def post(self, request, pk):
        form = CommentsForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.post_id = pk
            form.save()
        return redirect('/')

site_tb/templates/site_tb/question.html
{% load static %}
<html>
<head>
	<title>САЙТ ПО ОХРАНЕ ТРУДА</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />
	<link rel="shortcut icon" href="{% static 'css/images/favicon.ico' %}" />
</head>
<body>
<div class="shell">
	<div class="border">
		<div id="navigation">
			<ul class="active">
			    <li><a href="/">Главная</a></li>
			    <li><a href="/admin">Админ панель</a></li>
			</ul>
		</div>
		<div id="main">
			<div id="content">
				<div class="projects">
					<h3>Билеты по технике безопасности</h3>
					<div class="item">
					    <div class="image left">
							<h1>{{ ticket.title }}</h1>
							<br>
							<img src="{{ ticket.img.url }}" width="100%"/>
					    </div>
					    <div class="text left">
							{% for I in ticket.question_set.all %}
						<h3>{{ I.text_questions }}</h3>
							{{ I.answer_set.get }}
						<br><p>{{ text_answer }}</p>
                            {% endfor %}
						</div>
						<div class="cl"> </div>
				    </div>
			    </div>
			<div class="form-comment">
				<h3>Оставить комментарий</h3>
				<div>
					<form action="{% url 'add_comments' ticket.id %}" method="post">
						{%csrf_token%}
						<div class="comment-title">
							<label>Ваш комментарий</label>
						</div>
						<div><textarea name="text_comments" rows="7" cols="100"></textarea></div>
						<div class="comment-name">
							<label>Ваше имя</label>
							<input type="text" name="name" >
						</div>
						<div class="comment-mail">
							<label>Ваш email</label>
							<input type="email" name="email">
						</div>
						<div class="submit">
							<input type="submit">
						</div>
					</form>
				</div>
			</div>
				<div class = "view-comment">
			        {% for comment in ticket.comments_set.all %}
				    <h4>{{ comment.name  }}</h4>
				    <p>{{ comment.text_comments }}</p>
					<br>
					{% endfor %}
				</div>
				<div class="cl">&nbsp;</div>
			</div>
		</div>
	<div id="footer">
		<p class="copy right">Copyright &copy;  2023 </p>
	</div>
	</div>
</div>
</body>
</html>

site_tb/templates/site_tb/site_tb.html
{% load static %}
<html>
<head>
	<title>САЙТ ПО ОХРАНЕ ТРУДА</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />
	<link rel="shortcut icon" href="{% static 'css/images/favicon.ico' %}" />
</head>
<body>
<div class="shell">
	<div class="border">
		<div id="navigation">
			<ul class="active">
			    <li><a href="/">Главная</a></li>
			    <li><a href="/admin">Админ панель</a></li>
			</ul>
		</div>
		<div id="main">
			<div id="content">
				<div class="projects">
					<h3>Билеты по технике безопасности</h3>
					{% for ticket in ticket_list %}
					<div class="item">
                        <div class="image left">
							<img src="{{ ticket.img.url }}" width="600px" alt="" />
						</div>
						<div class="ticket-url" align="right">
							<h2><a href="{{ ticket.get_absolute_url }}">{{ ticket.title }}</a></h2>
						</div>
						<div class="cl">&nbsp;</div>
					</div>
					<p align="left"> Автор: {{ ticket.author }}</p>
					{% endfor %}
				</div>
			</div>
			<div class="cl">&nbsp;</div>
		</div>
	</div>
	<div id="footer">
		<p class="copy right">Copyright &copy;  2022 </p>
	</div>
</div>
</body>
</html>